CREATE TABLE products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    brand VARCHAR(255),
    short_description VARCHAR(500),
    description TEXT,
    category_id BIGINT REFERENCES categories(id),
    selling_price NUMERIC(10,2) NOT NULL,
    compare_price NUMERIC(10,2),
    cost_price NUMERIC(10,2),
    tax_percent NUMERIC(5,2) DEFAULT 0,
    sku VARCHAR(255),
    stock_qty INT NOT NULL DEFAULT 0,
    low_stock_threshold INT DEFAULT 5,
    allow_backorders BOOLEAN DEFAULT FALSE,
    weight_grams INT,
    dimension_l DOUBLE PRECISION,
    dimension_w DOUBLE PRECISION,
    dimension_h DOUBLE PRECISION,
    free_shipping BOOLEAN DEFAULT FALSE,
    meta_title VARCHAR(255),
    meta_description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP
);
